name: Docker Build&Publish
description: |
  Publish Docker-related images to a registry. You need to be logged in at the
  registry for this action to perform with success.

inputs:
  registry:
    required: true
    description: |
      The root of the registry, including "username" to publish to, e.g.
      msyea (to default to the docker hub), docker.io/msyea to make
      DockerHub explicit, or ghcr.io/msyea.
  version:
    required: false
    description: |
      The version of the Docker engine and rootless tools to use when
      building the images. Empty for latest (and tag will be short SHA)
  latest:
    required: false
    default: "false"
    description: |
      When set to `true` this will arrange to make the images generated the
      latest one.

outputs:
  version:
    description:
      Version of the Docker engine that was passed to the build stage, i.e.
      either the git short sha, or the incoming (request) semver.
    value: ${{ steps.output.outputs.version }}

runs:
  using: composite
  steps:
    # Guess the versions to use out of the values of the inputs and store these
    # in the environment.
    # + DOCKER_VERSION will be the incoming semver, or the git short SHA
    #   (understood as latest, e.g. current official release at build time)
    - name: Docker Version
      id: version
      shell: bash
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          printf DOCKER_VERSION=%s\\n "${{ inputs.version }}" >> "$GITHUB_ENV"
        else
          printf DOCKER_VERSION=%s\\n "$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
        fi
    - name: Output version
      id: output
      shell: bash
      run: ::set-output name=version::${{ env.DOCKER_VERSION }}

    # Setup multi-platform support for Docker build
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Build and Push the image to the remote registry, in turns.
    - name: Build/Push Docker to Registry
      id: docker
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile.docker
        tags: ${{ inputs.registry }}/ubuntu-docker:${{ env.DOCKER_VERSION }}
        platforms: linux/amd64,linux/arm64
        build-args: |
          DOCKER_VERSION=${{ env.DOCKER_VERSION }}
        push: true
    - name: Build/Push DinD to Registry
      id: dind
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile.dind
        tags: ${{ inputs.registry }}/ubuntu-dind:${{ env.DOCKER_VERSION }}
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          REGISTRY=${{ inputs.registry }}
          DOCKER_VERSION=${{ env.DOCKER_VERSION }}

    # Make the images latest if necessary.
    - name: Make Docker Images latest
      if: inputs.latest == 'true'
      shell: bash
      run: |
        docker image tag "${{ inputs.registry }}/ubuntu-docker:${{ env.DOCKER_VERSION }}" "${{ inputs.registry }}/ubuntu-docker:latest"
        docker image push "${{ inputs.registry }}/ubuntu-docker:latest"
        docker image tag "${{ inputs.registry }}/ubuntu-dind:${{ env.DOCKER_VERSION }}" "${{ inputs.registry }}/ubuntu-dind:latest"
        docker image push "${{ inputs.registry }}/ubuntu-dind:latest"
