name: Follow GH Runner Release Pace
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Runner Release Version
        id: runner
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: actions/runner
          exclude: prerelease, draft
      - name: Own Release Version
        id: own
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: ${{ github.repository }}
          exclude: prerelease, draft
      - name: Runner SemVer
        id: semver
        shell: bash
        run: |
          GH_RUNNER_VERSION=${{ steps.runner.outputs.release }}
          echo 'GH_RUNNER_VERSION='${GH_RUNNER_VERSION#v*} >> $GITHUB_ENV
      - name: Create Release
        if: steps.runner.outputs.release != steps.own.outputs.release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.GH_RUNNER_VERSION }}
          name: ${{ steps.runner.outputs.release }}
          draft: false
          prerelease: false