name: Publish Docker image

on:
  push:
  workflow_dispatch:

jobs:
  push:
    name: Push images to Docker Hub
    runs-on: ubuntu-latest
    if: secrets.DOCKERHUB_USERNAME != 0
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Images
        uses: ./.github/actions/publish@main
        with:
          registry: ${{ github.repository_owner }}
