name: Publish Docker image
on:
  push:
    tags-ignore:
      - '*.*.*'
  workflow_dispatch:

jobs:
  push_docker:
    name: Push Ubuntu Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set $GIT_SHORT_SHA
        run: echo "GIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.docker
          tags: ${{ github.repository_owner }}/ubuntu-docker:${{ env.GIT_SHORT_SHA }}
          build-args: |
            DOCKER_VERSION=${{ env.GIT_SHORT_SHA }}
          push: true
  push_dind:
    needs: push_docker
    name: Push Ubuntu DinD image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set $GIT_SHORT_SHA
        run: echo "GIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.dind
          tags: ${{ github.repository_owner }}/ubuntu-dind:${{ env.GIT_SHORT_SHA }}
          push: true
          build-args: |
            REGISTRY=${{ github.repository_owner }}
            DOCKER_VERSION=${{ env.GIT_SHORT_SHA }}
  push_gha:
    needs: [push_docker, push_dind]
    name: Push GitHub Actions runner image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set $GIT_SHORT_SHA
        run: echo "GIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: ${{ github.repository_owner }}/github-actions-runner:${{ env.GIT_SHORT_SHA }}
          push: true
          build-args: |
            REGISTRY=${{ github.repository_owner }}
            DOCKER_VERSION=${{ env.GIT_SHORT_SHA }}
