name: Publish to DockerHub

on:
  push:
  workflow_dispatch:

jobs:
  push:
    name: Push images to DockerHub
    runs-on: ubuntu-latest
    env:
      HAVE_ACCESS: ${{ secrets.DOCKERHUB_USERNAME != '' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: env.HAVE_ACCESS == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Images
        if: env.HAVE_ACCESS == 'true'
        uses: ./.github/actions/publish
        with:
          registry: ${{ github.repository_owner }}
