name: Publish to GHCR
on:
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - 'Dockerfile*'
      - 'dind'
      - '.github/actions/**'
      - '.github/workflows/github-packages-publish.yml'
  workflow_dispatch:

jobs:
  push:
    name: Push images to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Images
        uses: ./.github/actions/image
        id: docker
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-docker
          variable: DOCKER_VERSION
          dockerfile: ./Dockerfile.docker
      - name: Build and Push DinD Images
        uses: ./.github/actions/image
        id: dind
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-dind
          variable: DOCKER_VERSION
          dockerfile: ./Dockerfile.dind
      - name: Build and Push git Images
        uses: ./.github/actions/image
        id: git
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-git
          variable: GIT_VERSION
          dockerfile: ./Dockerfile.git
      - name: Build and Push Runner Images
        uses: ./.github/actions/runner
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: github-actions-runner
          variable: GH_RUNNER_VERSION
          dockerfile: ./Dockerfile
          build-args: |
            DOCKER_VERSION=${{ steps.docker.outputs.version }}
            GIT_VERSION=${{ steps.git.outputs.version }}
