# Whenever we push a (relevant) change to the code, try to generate test images
# at the GHCR, and just for Intel. Images will be tagged with the GIT short SHA
# and can be used for testing purposes, e.g. when setting up a test runner in
# k8s.
name: dev/GHCR
on:
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - 'Dockerfile*'
      - 'dind'
      - '.github/actions/**'
      - '.github/workflows/github-packages-publish.yml'
  workflow_dispatch:

jobs:
  push:
    name: Push images to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      # Setup multi-platform support for Docker build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: ./.github/actions/image
        id: docker
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-docker
          variable: DOCKER_VERSION
          dockerfile: ./Dockerfile.docker
      - name: Build and Push DinD Image
        uses: ./.github/actions/image
        id: dind
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-dind
          variable: DOCKER_VERSION
          dockerfile: ./Dockerfile.dind
      - name: Build and Push git Image
        uses: ./.github/actions/image
        id: git
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-git
          variable: GIT_VERSION
          dockerfile: ./Dockerfile.git
      - name: Build and Push Runner Image
        uses: ./.github/actions/image
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: github-actions-runner
          variable: GH_RUNNER_VERSION
          dockerfile: ./Dockerfile
          build-args: |
            DOCKER_VERSION=${{ steps.docker.outputs.version }}
            GIT_VERSION=${{ steps.git.outputs.version }}
            USER_RUNNER=rootless
