name: Publish Docker image to GitHub
on:
  push:
  workflow_dispatch:

jobs:
  push:
    name: Push images to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Images
        uses: ./.github/actions/publish
        with:
          registry: ghcr.io/${{ github.repository }}
