name: Publish to GHCR
on:
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - 'Dockerfile*'
      - 'dind'
      - '.github/actions/**'
      - '.github/workflows/github-package-publish.yml'
  workflow_dispatch:

jobs:
  push:
    name: Push images to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Images
        uses: ./.github/actions/docker
        id: docker
        with:
          registry: ghcr.io/${{ github.repository }}
      - name: Build and Push Runner Images
        uses: ./.github/actions/runner
        with:
          registry: ghcr.io/${{ github.repository }}
          docker: ${{ steps.docker.outputs.version }}
