name: Manual Release

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        description: |
          Pure SemVer version of the official GitHub runner to generate a
          rootless Docker image for. NO LEADING `v`!
          see: https://github.com/actions/runner/releases
      git:
        required: false
        description: |
          Pure SemVer version of git to use in rootless Docker image. NO LEADING
          `v`!
          see: https://github.com/git/git/tags
      docker:
        required: false
        description: |
          Pure SemVer version of docker to use in rootless Docker image. NO
          LEADING `v`!
          see: https://github.com/moby/moby/releases

jobs:
  docker:
    name: Docker (moby)
    uses: ./.github/workflows/_release.yml
    with:
      project: moby/moby
      image: ubuntu-docker
      variable: DOCKER_VERSION
      dockerfile: ./Dockerfile.docker
      version: ${{ github.event.inputs.docker }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  dind:
    name: Docker in Docker
    needs:
      - docker
    uses: ./.github/workflows/_release.yml
    with:
      project: moby/moby
      image: ubuntu-dind
      variable: DOCKER_VERSION
      dockerfile: ./Dockerfile.dind
      version: ${{ github.event.inputs.docker }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  git:
    name: git
    uses: ./.github/workflows/_release.yml
    with:
      project: git/git
      image: ubuntu-git
      variable: GIT_VERSION
      dockerfile: ./Dockerfile.git
      version: ${{ github.event.inputs.git }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  runner:
    name: GitHub Runner
    needs:
      - dind
      - git
    uses: ./.github/workflows/_release.yml
    with:
      project: actions/runner
      image: github-actions-runner
      variable: GH_RUNNER_VERSION
      dockerfile: ./Dockerfile
      version: ${{ github.event.inputs.runner }}
      build-args: |
        DOCKER_VERSION=${{ needs.dind.outputs.version }}
        GIT_VERSION=${{ needs.git.outputs.version }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  release:
    name: Release Runner
    needs:
      - runner
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # Create a release at GitHub, this arranges for the comparison step to
      # work next time. Release is created last, so it acts as a marker that
      # Docker image publication steps have succeeded. Release name contains
      # leading `v`, release tag **without** the leading `v`.
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.runner.outputs.version }}
          name: v${{ needs.runner.outputs.version }}
          body: |
            Automatic release to match new GH Actions runner [release]. See all
            versions and pull instructions [here][images]. Main generated GHCR
            image called `${{ needs.runner.outputs.image }}`.

              [release]: https://github.com/actions/runner/releases/tag/v${{ needs.runner.outputs.version }}
              [images]: https://github.com/${{ github.repository }}/pkgs/container/github-actions-runner-rootless%2Fgithub-actions-runner
          draft: false
          prerelease: false
