# On PR, we want to make sure things will work when the PR is merged. Build
# everything from scratch, just for Intel for a quicker process, and pull/push
# to a local registry as we: 1. do not want to pollute the GHCR or DockerHub, 2.
# Want to test the entire process.
name: PR
on:
  pull_request:
  workflow_dispatch:

jobs:
  push:
    name: Build Intel Images
    runs-on: ubuntu-latest
    # Create a local registry so we can run a complete test, including
    # pushing/pulling from registry if necessary.
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      # Setup multi-platform support for Docker build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      # Build all images, one at a time
      - name: Build Docker Image
        uses: ./.github/actions/image
        id: docker
        with:
          registry: localhost:5000/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-docker
          variable: DOCKER_VERSION
          dockerfile: ./Dockerfile.docker
      - name: Build DinD Image
        uses: ./.github/actions/image
        id: dind
        with:
          registry: localhost:5000/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-dind
          variable: DOCKER_VERSION
          dockerfile: ./Dockerfile.dind
      - name: Build git Image
        uses: ./.github/actions/image
        id: git
        with:
          registry: localhost:5000/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-git
          variable: GIT_VERSION
          dockerfile: ./Dockerfile.git
      - name: Build Runner Image
        uses: ./.github/actions/image
        with:
          registry: localhost:5000/${{ github.repository }}
          platforms: linux/amd64
          image: github-actions-runner
          variable: GH_RUNNER_VERSION
          dockerfile: ./Dockerfile
          build-args: |
            DOCKER_VERSION=${{ steps.docker.outputs.version }}
            GIT_VERSION=${{ steps.git.outputs.version }}
