name: PR
on:
  pull_request:
  workflow_dispatch:

jobs:
  push:
    name: Build Intel Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build Docker Image
        uses: ./.github/actions/image
        id: docker
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-docker
          variable: DOCKER_VERSION
          dockerfile: ./Dockerfile.docker
          push: "false"
      - name: Build DinD Image
        uses: ./.github/actions/image
        id: dind
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-dind
          variable: DOCKER_VERSION
          dockerfile: ./Dockerfile.dind
          push: "false"
      - name: Build git Image
        uses: ./.github/actions/image
        id: git
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: ubuntu-git
          variable: GIT_VERSION
          dockerfile: ./Dockerfile.git
          push: "false"
      - name: Build Runner Image
        uses: ./.github/actions/image
        with:
          registry: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          image: github-actions-runner
          variable: GH_RUNNER_VERSION
          dockerfile: ./Dockerfile
          push: "false"
          build-args: |
            DOCKER_VERSION=${{ steps.docker.outputs.version }}
            GIT_VERSION=${{ steps.git.outputs.version }}
