name: Release images to GitHub Repository and DockerHub
on:
  push:
    branches:
      - "main"
    tags:
      - '*.*.*'

jobs:
  # Detect current version of Docker (engine) and arrange for the `version`
  # output to be called after the pure SemVer of the release, i.e. 20.10.12
  # (without the leading `v`).
  docker_version:
    name: Docker SemVer
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version }}
    steps:
      - name: Docker Release Version
        id: docker
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: moby/mody
          excludes: prerelease, draft
      - name: Docker SemVer
        id: semver
        shell: bash
        run: |
          DOCKER_VERSION=${{ steps.docker.outputs.release }}
          echo 'DOCKER_VERSION='${DOCKER_VERSION#v*} >> $GITHUB_ENV
          echo "::set-output name=version::${DOCKER_VERSION#v*}"

  # Publish the various images to the GHCR. The Docker images will be tagged as
  # of the version of the Docker engine that they are based on. The current
  # setup might re-build the Docker images, but they should lead to the same
  # content anyway. The GH Runner image will be tagged with the same SemVer
  # version as the runner, i.e. 2.286.0 (without the leading `v`)
  publish_github_ubuntu_docker:
    needs: docker_version
    name: Push Ubuntu Docker image to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.docker
          build-args: |
            DOCKER_VERSION=${{ jobs.docker_version.version }}
          tags: |
            docker.pkg.github.com/${{ github.repository_owner }}/github-actions-runner/ubuntu-docker:latest
            docker.pkg.github.com/${{ github.repository_owner }}/github-actions-runner/ubuntu-docker:${{ jobs.docker_version.version }}
          push: true
  publish_github_ubuntu_dind:
    needs: [docker_version, publish_github_ubuntu_docker]
    name: Push Ubuntu DinD image to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull docker.pkg.github.com/${{ github.repository_owner }}/github-actions-runner/ubuntu-docker:${{ jobs.docker_version.version }}
      - name: Push to GitHub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.dind
          tags: |
            docker.pkg.github.com/${{ github.repository_owner }}/github-actions-runner/ubuntu-dind:latest
            docker.pkg.github.com/${{ github.repository_owner }}/github-actions-runner/ubuntu-dind:${{ jobs.docker_version.version }}
          push: true
          build-args: |
            REGISTRY=docker.pkg.github.com/${{ github.repository_owner }}/github-actions-runner
            DOCKER_VERSION=${{ jobs.docker_version.version }}
  publish_github_github_actions_runner:
    needs: [docker_version, publish_github_ubuntu_docker, publish_github_ubuntu_dind]
    name: Push GitHub Actions runner image to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull docker.pkg.github.com/${{ github.repository_owner }}/github-actions-runner/ubuntu-dind:${{ jobs.docker_version.version }}
      - name: Push to GitHub
        uses: docker/build-push-action@v2
        with:
          tags: |
            docker.pkg.github.com/${{ github.repository_owner }}/github-actions-runner/github-actions-runner:latest
            docker.pkg.github.com/${{ github.repository_owner }}/github-actions-runner/github-actions-runner:${{ github.ref_name }}
          push: true
          build-args: |
            REGISTRY=docker.pkg.github.com/${{ github.repository_owner }}/github-actions-runner
            DOCKER_VERSION=${{ jobs.docker_version.version }}
            GH_RUNNER_VERSION=${{ github.ref_name }}

  # Publish the various images to the Docker Hub. The Docker images will be
  # tagged as of the version of the Docker engine that they are based on. The
  # current setup might re-build the Docker images, but they should lead to the
  # same content anyway. The GH Runner image will be tagged with the same SemVer
  # version as the runner, i.e. 2.286.0 (without the leading `v`)
  publish_docker_ubuntu_docker:
    needs: docker_version
    name: Push Ubuntu Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.docker
          build-args: |
            DOCKER_VERSION=${{ jobs.docker_version.version }}
          tags: |
            ${{ github.repository_owner }}/ubuntu-docker:latest
            ${{ github.repository_owner }}/ubuntu-docker:${{ jobs.docker_version.version }}
          push: true
  publish_docker_ubuntu_dind:
    needs: [docker_version, publish_docker_ubuntu_docker]
    name: Push Ubuntu DinD image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.dind
          tags: |
            ${{ github.repository_owner }}/ubuntu-dind:latest
            ${{ github.repository_owner }}/ubuntu-dind:${{ jobs.docker_version.version }}
          push: true
          build-args: |
            REGISTRY=${{ github.repository_owner }}
            DOCKER_VERSION=${{ jobs.docker_version.version }}
  publish_docker_github_actions_runner:
    needs: [docker_version, publish_docker_ubuntu_docker, publish_docker_ubuntu_dind]
    name: Push GitHub Actions runner image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: |
            ${{ github.repository_owner }}/github-actions-runner:latest
            ${{ github.repository_owner }}/github-actions-runner:${{ github.ref_name }}
          push: true
          build-args: |
            REGISTRY=${{ github.repository_owner }}
            DOCKER_VERSION=${{ jobs.docker_version.version }}
            GH_RUNNER_VERSION=${{ github.ref_name }}
